# Generated by Django 3.0.5 on 2021-01-13 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CassavaArea',
            fields=[
                ('cassavaAreaId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treeLatitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('treeLongtitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('treewidth', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('treeLong', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='FarmStore',
            fields=[
                ('farmId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmName', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('plantingDate', models.DateField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('longtitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='UidStore',
            fields=[
                ('email', models.EmailField(max_length=40)),
                ('uId', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starch_percentage', models.FloatField(max_length=6)),
                ('checkDate', models.DateField(default=django.utils.timezone.localdate)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmStore', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.FarmStore')),
            ],
        ),
        migrations.AddField(
            model_name='farmstore',
            name='uidStore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.UidStore'),
        ),
        migrations.CreateModel(
            name='CassavaCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkDate', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('longtitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('spectrum1', models.FloatField(max_length=20)),
                ('spectrum2', models.FloatField(max_length=20)),
                ('spectrum3', models.FloatField(max_length=20)),
                ('spectrum4', models.FloatField(max_length=20)),
                ('semperature', models.FloatField(max_length=20)),
                ('starchPercentage', models.FloatField(max_length=20)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cassavaArea', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.CassavaArea')),
            ],
        ),
        migrations.AddField(
            model_name='cassavaarea',
            name='farmStore',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.FarmStore'),
        ),
    ]
