# Generated by Django 3.0.5 on 2021-01-15 02:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CassavaArea',
            fields=[
                ('cassava_area_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starch_percentage', models.FloatField(max_length=20)),
                ('tree_latitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('tree_longtitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='FarmStore',
            fields=[
                ('farm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('planting_date', models.DateField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('longtitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('latitude_mark1', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('longtitude_mark1', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('latitude_mark2', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('longtitude_mark2', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('latitude_mark3', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('longtitude_mark3', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('latitude_mark4', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('longtitude_mark4', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='UidStore',
            fields=[
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('uId', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starch_percentage', models.FloatField(max_length=6)),
                ('check_date', models.DateField(default=django.utils.timezone.localdate)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farm_store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.FarmStore')),
            ],
        ),
        migrations.AddField(
            model_name='farmstore',
            name='uid_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.UidStore'),
        ),
        migrations.CreateModel(
            name='CassavaCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('longtitude', models.DecimalField(decimal_places=15, default=0, max_digits=30)),
                ('spectrum1', models.FloatField(max_length=20)),
                ('spectrum2', models.FloatField(max_length=20)),
                ('spectrum3', models.FloatField(max_length=20)),
                ('spectrum4', models.FloatField(max_length=20)),
                ('spectrum5', models.FloatField(max_length=20)),
                ('spectrum6', models.FloatField(max_length=20)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starchPercentage', models.FloatField(max_length=20)),
                ('cassava_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.CassavaArea')),
            ],
        ),
        migrations.AddField(
            model_name='cassavaarea',
            name='farm_store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.FarmStore'),
        ),
    ]
