# Generated by Django 3.0.5 on 2021-01-27 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassavacheck',
            name='check_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
